# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7ffad52703e8e61c28fc08bbed1cbab71a3faca85eb7eca8a28a29dc73f73224bce8744eafd2356cde91eda2c8fb6e706eb2dd04906727930ced7b425f53240

test:
  secret_key_base: e3c65b51808884e4e07ff538d102b30cd783106fc5b67146ad45558ade9baa6a704efd2902ceaf938be2b719eb0c5d7e92ccb579f0ab3a9671f97662bfc997cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: a50d2f11b68855665efe52e1b7563e196cfd0d3855ff550c99d091c0de7ac72a7559ca96e19c0e1864142aa4ed4a043ace4d2720a46d66a6ea11effad1f0c675
